# Generated by Django 4.1.4 on 2022-12-24 07:28

import advertisement.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('meta_data', models.JSONField(null=True)),
                ('name', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=15)),
                ('ad_priority', models.CharField(choices=[('LOW', 'LOW'), ('MID', 'MID'), ('HIGH', 'HIGH')], default=advertisement.enums.AdPriorityType['HIGH'], max_length=15)),
                ('ad_status', models.CharField(choices=[('LOW', 'LOW'), ('MID', 'MID'), ('HIGH', 'HIGH')], default=advertisement.enums.AdPriorityType['HIGH'], max_length=15)),
            ],
            options={
                'db_table': 'advertisement',
            },
        ),
    ]
