# Generated by Django 4.1.4 on 2022-12-25 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0003_bqexampledata'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bqexampledata',
            table='bq_example_data',
        ),
    ]
